// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

// ✅ Done
import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ColorThemeController from "./color_theme_controller"
application.register("color-theme", ColorThemeController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

// ✅ My Implementation to see how it works with sending user info from backend to frontend
import HelloUserController from "./hello_user_controller"
application.register("hello-user", HelloUserController)

// ✅ My Implementation to see how to fetch and use API weather data
import WeatherController from "./weather_controller"
application.register("weather", WeatherController)

// ✅ Redirecting page from Index to Quotes when no quotes are present
import NoQuotesController from "./no_quotes_controller";
application.register("no-quotes", NoQuotesController);
